---
- hosts: all
  name: Primeiro playbook
  become: yes


  tasks:
    - name: Create group
      group:
        name: redhatters
        state: present

    - name: Create user
      user:
        name: Bob
        uid: 1040
        group: redhatters
        shell: /bin/bash

    - name: Enable 161-162
      firewalld:
        port: 161-162/udp
        permanent: yes
        state: enabled


    - name: Disable firewall 8081
      firewalld:
        port: 8081/tcp
        permanent: yes
        state: disabled

    - name: Install the apache server
      yum:
        name: httpd
        state: present

    - name: Start httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Subir o html
      copy:
        src: /etc/ansible/roles/index.html
        dest: /var/www/html/index.html

    - name: Restart httpd
      service:
        name: httpd
        state: restarted
